spring:
  application:
    name: movie-library-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/movie_library}
    username: ${SPRING_DATASOURCE_USERNAME:movielibraryservice}
    password: ${SPRING_DATASOURCE_PASSWORD:dev}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1100MB

app:
  digikat:
    base-url: https://digikat.pl
    connection-timeout-ms: 5000
    read-timeout-ms: 10000
    max-retries: 3
  movie:
    small-file-size: 209715200
  upload:
    directory: C:\REPO\move-web\movie